global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:

  # =========================================================
  # 📊 PROMETHEUS SELF MONITORING
  # =========================================================
  - job_name: "prometheus"

    static_configs:
      - targets:
          - "prometheus:9090"

  # =========================================================
  # 🔥 TRIVY EXPORTER METRICS
  # =========================================================
  - job_name: "trivy-exporter"

    metrics_path: "/metrics"

    static_configs:
      - targets:
          - "trivy-exporter:8000"
